version: '2'

services:

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/coeus
      - /coeus/node_modules/
#    command: "tail -f /dev/null"
    environment:
      CHOKIDAR_USEPOLLING: 1